name: Deploy Application - Prod

concurrency: app-prod

permissions:
  id-token: write
  contents: read
  actions: read

on:
  push:
    branches: ["main"]
    paths:
      - 'infrastructure/**'
      - 'client/**'
      # - 'backend/**'
  workflow_dispatch:

jobs:
  build:
    uses: wlindb/astraterial/.github/workflows/cdk-deploy.yml@main
    with:
      env: prod
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
      aws-secret-key: ${{ secrets.AWS_SECRET_KEY_PROD }}
      cms-read-api-key: ${{ secrets.CMS_READ_API_KEY_DEV }}

