name: CDK Deploy

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      env:
        type: string
        description: 'Environment'
        required: true
    secrets:
      aws-access-key-id:
        description: 'AWS Access Key ID'
        required: true
      aws-secret-key:
        description: 'AWS Secret Key'
        required: true
      cms-read-api-key:
        description: 'CMS Read API key'
        required: true
      analytics-api-key:
        description: 'Analytics API key'
        required: true

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Install AWS CDK
        run: npm i -g aws-cdk

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-key }}
          aws-region: "eu-north-1"

      - name: Synth stack
        run: |
          cdk synth --context env=${{ inputs.env }} \
          --context CMS_READ_API_KEY=${{ secrets.cms-read-api-key }} \
          --context ANALYTICS_API_KEY=${{ secrets.analytics-api-key }} 

      - name: Deploy stack
        run: |
          cdk deploy --all --context env=${{ inputs.env }} \
          --context CMS_READ_API_KEY=${{ secrets.cms-read-api-key }} \
          --context ANALYTICS_API_KEY=${{ secrets.analytics-api-key }} \
          --require-approval never --progress events

