name: Deploy Client Dev

permissions:
  id-token: write
  contents: read
  actions: read

on:
  push:
    branches: ["develop"]
    paths:
      - 'client/**'
  workflow_dispatch:

jobs:
  build:
    uses: wlindb/astraterial/.github/workflows/ecr-deploy.yml@main
    with:
      env: dev
      base-url: https://dev.astraterial.com
      cms-base-url: https://d2gcu6a9g33c1.cloudfront.net/cms/read/en-US
      working-directory: client
      region: eu-central-1
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-key: ${{ secrets.AWS_SECRET_KEY }}
      cms-read-api-key: ${{ secrets.CMS_READ_API_KEY_DEV }}

